-- Syncing inline migrations from main.go to ensure schema history is complete
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(50) NOT NULL DEFAULT '';

ALTER TABLE contracts 
    ADD COLUMN IF NOT EXISTS electricity_bill DECIMAL(10,2) NOT NULL DEFAULT 0, 
    ADD COLUMN IF NOT EXISTS water_bill DECIMAL(10,2) NOT NULL DEFAULT 0, 
    ADD COLUMN IF NOT EXISTS other_bills DECIMAL(10,2) NOT NULL DEFAULT 0;

ALTER TABLE rooms 
    ADD COLUMN IF NOT EXISTS floor VARCHAR(50) NOT NULL DEFAULT '1', 
    ADD COLUMN IF NOT EXISTS is_draft BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS type VARCHAR(100) NOT NULL DEFAULT '';
